ALTER TABLE players ADD COLUMN IF NOT EXISTS region VARCHAR(4) NOT NULL DEFAULT 'NA';
ALTER TABLE players ADD COLUMN IF NOT EXISTS level INTEGER NOT NULL DEFAULT 1;

CREATE INDEX IF NOT EXISTS idx_players_region ON players (region);
